const content = {
  Footer: {
    title: "Digitize every clinic touchpoint with DardiBook.",
    description:
      "Practice management software for appointments, patient records, prescriptions, diagnostics, pharmacy coordination, and follow-ups.",
    bookWalkthrough: "Book a product walkthrough",
    proof1Title: "Privacy-first workflows",
    proof1Desc:
      "Built around responsible handling of clinic and patient data.",
    proof2Title: "Guided setup",
    proof2Desc:
      "Map your current reception, consultation, and follow-up flow.",
    proof3Title: "Fast daily use",
    proof3Desc: "Designed for busy teams that need clarity during OPD hours.",
    productTitle: "Product",
    productPatientRecords: "Patient Records",
    productAppointments: "Appointments",
    productPrescriptions: "Prescriptions",
    productDiagnostics: "Diagnostics",
    solutionsTitle: "Solutions",
    solutionsSoloDoctors: "Solo Doctors",
    solutionsClinics: "Clinics",
    solutionsHospitals: "Hospitals",
    solutionsCareTeams: "Care Teams",
    workflowsTitle: "Workflows",
    workflowsPatientJourney: "Patient Journey",
    workflowsClinicQueue: "Clinic Queue",
    workflowsLabPharmacy: "Lab & Pharmacy",
    workflowsFollowups: "Follow-ups",
    companyTitle: "Company",
    companyBookDemo: "Book Demo",
    companyImplementation: "Implementation",
    companyTrustAccess: "Trust & Access",
    companyContact: "Contact",
    legalTitle: "Legal",
    legalAbout: "About",
    legalPricing: "Pricing",
    legalPrivacyPolicy: "Privacy Policy",
    legalTermsConditions: "Terms & Conditions",
    legalCancellationPolicy: "Cancellation Policy",
    copyright: "© {year} DardiBook, All rights reserved",
  },
  CallToAction: {
    title: "Ready to see DardiBook inside your clinic workflow?",
    description:
      "Book a walkthrough for your team. We will map your current reception, consultation, prescription, lab, and follow-up process to the right DardiBook setup.",
    bookDemo: "Book a Demo",
    pricingTitle: "Simple clinic pricing",
    pricingDesc:
      "Choose a plan around your users, branches, and workflow needs without paying for modules you do not use.",
    onboardingTitle: "Guided onboarding",
    onboardingDesc:
      "Get help setting up patient records, staff roles, appointment flow, prescriptions, and diagnostics from day one.",
  },
  FeaturesSequence: {
    headerSubtitle: "Designed for care teams",
    headerTitle: "Run your practice with less admin and more clarity",
    headerDesc:
      "DardiBook brings appointments, patient records, prescriptions, lab requests, follow-ups, and clinic activity into one simple workspace so doctors and staff can spend more time on patient care.",
    exploreModules: "Explore modules",
    todayLabel: "Today",
    clinicDeskTitle: "Clinic desk",
    liveLabel: "Live",
    waitingLabel: "Waiting",
    waitingValue: "12 patients",
    prescriptionsLabel: "Prescriptions",
    prescriptionsValue: "28 issued",
    labReportsLabel: "Lab reports",
    labReportsValue: "7 pending",
    nextConsultationLabel: "Next consultation",
    f1Title: "Digital Patient Records",
    f1Desc:
      "Keep medical history, visits, prescriptions, files, and notes organized for quick review during every consultation.",
    f1Cta: "View records",
    f2Title: "Appointment Workflow",
    f2Desc:
      "Manage bookings, queues, reminders, and follow-ups from one place without losing track of the day.",
    f2Cta: "See scheduling",
    f3Title: "Prescription & Lab Flow",
    f3Desc:
      "Create digital prescriptions and connect recommended tests with diagnostics for smoother patient handoffs.",
    f3Cta: "Explore care flow",
    f4Title: "Secure Practice Data",
    f4Desc:
      "Protect clinic information with role-aware access and a digital workflow built for responsible healthcare use.",
    f4Cta: "Review access",
  },
  TrustProof: {
    title: "Why clinics choose DardiBook",
    subtitle: "Less manual work, better patient continuity",
    description:
      "The strongest healthcare software feels calm during a busy clinic day. DardiBook keeps the essentials visible without forcing teams into a complicated enterprise system.",
    i1Title: "Secure clinic records",
    i1Desc:
      "Keep sensitive patient information organized with privacy-first digital workflows.",
    i2Title: "Role-based staff access",
    i2Desc:
      "Give reception, doctors, and operations teams the right view for their work.",
    i3Title: "Fast onboarding",
    i3Desc:
      "Start with core clinic workflows first, then expand into pharmacy, labs, and follow-ups.",
    i4Title: "Built for teams",
    i4Desc:
      "Works for solo doctors, growing clinics, hospitals, pharmacies, and diagnostics.",
  },
  ObjectionsAccordion: {
    title: "Frequently Asked Questions",
    description: "Everything you need to know about our product, billing, and how we keep your data secure. Select a topic below to explore.",
    
    contactTitle: "Still have questions?",
    contactDesc: "Can't find the answer you're looking for? Our friendly team is ready to help you get the most out of our platform.",
    contactButton: "Contact Support",
  },
  FAQData: [
    {
      id: "general",
      title: "General Questions",
      items: [
        { question: "What is this product and how does it work?", answer: "Our platform provides a seamless experience for managing your daily tasks. It connects to your existing tools and automates repetitive workflows." },
        { question: "Who is this solution built for?", answer: "It is designed for small to medium-sized teams who want to scale their operations without compromising on quality or spending hours on manual data entry." },
      ]
    },
    {
      id: "pricing",
      title: "Pricing & Billing",
      items: [
        { question: "Is there a free trial available?", answer: "Yes! We offer a 14-day free trial on all of our premium plans. No credit card is required to sign up." },
        { question: "Can I change my plan later?", answer: "Absolutely. You can upgrade or downgrade your plan at any time directly from your billing dashboard. Changes are prorated automatically." },
      ]
    },
    {
      id: "support",
      title: "Support & Security",
      items: [
        { question: "How do I contact customer support?", answer: "You can reach out to our support team 24/7 via the live chat widget in the bottom right corner, or by emailing support." },
        { question: "Is my data secure?", answer: "Security is our top priority. We use industry-standard AES-256 encryption and are fully SOC2 and GDPR compliant." },
      ]
    }
  ],

  Workflow: {
    title: "How DardiBook works",
    subtitle: "A complete patient journey from entry to follow-up",
    description:
      "DardiBook is built around the way clinics actually move: reception, consultation, prescription, diagnostics, and continued care.",
    s1Title: "Register Patient",
    s1Desc:
      "Create a patient profile once and keep demographics, visits, files, and care notes organized.",
    s2Title: "Consultation",
    s2Desc:
      "Doctors can review history, capture clinical notes, and keep each visit linked to the patient record.",
    s3Title: "Prescription",
    s3Desc:
      "Generate clear digital prescriptions with medicine, dosage, advice, and revisit instructions.",
    s4Title: "Lab & Pharmacy",
    s4Desc:
      "Connect test requests, pharmacy details, and reports back to the same visit for better continuity.",
    s5Title: "Follow-up",
    s5Desc:
      "Track pending care tasks and follow-up reminders so patients do not disappear after the visit.",
  },
  LogoCloud: {
    title: "Trusted by Healthcare Professionals",
    description:
      "DardiBook supports clinics, hospitals, pharmacies, diagnostics, and solo practitioners. Designed for modern medical workflows.",
    l1: "Clinics",
    l2: "Hospitals",
    l3: "Solo Doctors",
    l4: "Reception Teams",
    l5: "Care Coordinators",
    l6: "Patient Records",
    l7: "Appointments",
    l8: "Prescriptions",
    l9: "Lab Requests",
    l10: "Follow-ups",
    l11: "Pharmacies",
    l12: "Diagnostics",
    l13: "Specialists",
    l14: "Medical Staff",
    l15: "Patients",
  },
  Hero: {
    title: "Digitize your medical practice with DardiBook",
    description:
      "Manage appointments, patient records, prescriptions, lab requests, and follow-ups from one secure workspace built for doctors and clinic teams.",
    requestDemo: "Request Demo",
    seeWorkflow: "See Workflow",
    dummyClinic: "DardiBook Clinic",
  },
  Navbar: {
    menuWorkflow: "Workflow",
    menuModules: "Modules",
    menuTrust: "Trust",
    menuDemo: "Demo",
    modPatientRecordsTitle: "Patient Records",
    modPatientRecordsDesc:
      "Profiles, medical history, visit notes, files, and case context in one place.",
    modAppointmentsTitle: "Appointments",
    modAppointmentsDesc:
      "Clinic schedules, walk-ins, queues, visit status, and follow-up planning.",
    modPrescriptionsTitle: "Prescriptions",
    modPrescriptionsDesc:
      "Digital prescriptions with medicine, dosage, advice, and revisit instructions.",
    modDiagnosticsTitle: "Diagnostics",
    modDiagnosticsDesc:
      "Lab requests and reports connected to the right patient visit.",
    solSoloDoctorsTitle: "Solo Doctors",
    solSoloDoctorsDesc:
      "A simple digital workflow for independent practices.",
    solClinicsTitle: "Clinics",
    solClinicsDesc:
      "Reception, doctors, pharmacy, and lab teams working from one system.",
    solHospitalsTitle: "Hospitals",
    solHospitalsDesc:
      "Structured records and role-aware workflows for larger teams.",
    solCareTeamsTitle: "Care Teams",
    solCareTeamsDesc:
      "Better coordination across staff, patients, pharmacies, and diagnostics.",
    brandName: "DardiBook",
    requestDemo: "Request Demo",
  },
  CardCarousel: {
    title: "Built for healthcare teams",
    description: "See how DardiBook connects your clinic's workflow.",
    dragToExplore: "Drag to explore",
    c1Title: "Clinics & Hospitals",
    c1Eyebrow: "Operations",
    c1Desc:
      "Digitize front-desk, consultation, prescription, and follow-up workflows in one practical clinic management system.",
    c1Stat: "One connected desk",
    c1T1: "Queues",
    c1T2: "Records",
    c1T3: "Reports",
    c2Title: "Doctors",
    c2Eyebrow: "Consultation",
    c2Desc:
      "Review patient history, write prescriptions, request tests, and continue care with fewer administrative interruptions.",
    c2Stat: "Faster visits",
    c2T1: "History",
    c2T2: "Rx",
    c2T3: "Notes",
    c3Title: "Patients",
    c3Eyebrow: "Care journey",
    c3Desc:
      "Give patients a smoother journey with organized visits, clearer instructions, digital prescriptions, and timely follow-ups.",
    c3Stat: "Better continuity",
    c3T1: "Visits",
    c3T2: "Advice",
    c3T3: "Follow-up",
    c4Title: "Pharmacies",
    c4Eyebrow: "Medicine flow",
    c4Desc:
      "Read prescription details clearly, reduce manual clarification, and support faster medicine fulfillment.",
    c4Stat: "Clearer Rx",
    c4T1: "Dosage",
    c4T2: "Medicine",
    c4T3: "Refills",
    c5Title: "Diagnostics",
    c5Eyebrow: "Lab workflow",
    c5Desc:
      "Link lab requests and reports with patient visits so doctors can review results in the right clinical context.",
    c5Stat: "Linked reports",
    c5T1: "Tests",
    c5T2: "Reports",
    c5T3: "Review",
    c6Title: "Healthcare Platforms",
    c6Eyebrow: "Ecosystem",
    c6Desc:
      "Extend patient engagement and care coordination with modules built around real clinic workflows.",
    c6Stat: "Modular setup",
    c6T1: "Integrations",
    c6T2: "Teams",
    c6T3: "Care",
    c7Title: "Medical Institutions",
    c7Eyebrow: "Institutional care",
    c7Desc:
      "Support institutional operations with structured case histories, visit records, and repeatable care processes.",
    c7Stat: "Structured cases",
    c7T1: "Training",
    c7T2: "Cases",
    c7T3: "Records",
    headerTitle: "Built for every kind of healthcare provider",
    headerDescription:
      "From small clinics to growing hospitals, and from individual doctors to diagnostic labs, DardiBook helps reduce administrative workload while improving patient continuity.",
  },
  GridCarousel: {
    title: "Tailored to your practice",
    subtitle: "Configured for the way your team works.",
    s0Title: "Multi-speciality Clinics",
    s0Stats: "One desk",
    s0Desc:
      "Appointments, visits, prescriptions, and reports coordinated across departments.",
    s0P1: "Patient Records",
    s0P2: "Appointments",
    s0Metric: "6",
    s0MetricLabel: "departments aligned",
    s0Action: "Route patient to cardiology",
    s0Q1L: "Reception",
    s0Q1V: "12 waiting",
    s0Q2L: "Doctors",
    s0Q2V: "6 in consultation",
    s0Q3L: "Diagnostics",
    s0Q3V: "7 reports pending",
    s1Title: "Growing Hospitals",
    s1Stats: "Central view",
    s1Desc:
      "Daily operations organized for doctors, reception, pharmacy, and diagnostic teams.",
    s1P1: "Queue Flow",
    s1P2: "Care Tasks",
    s1Metric: "124",
    s1MetricLabel: "visits tracked today",
    s1Action: "Review pending care tasks",
    s1Q1L: "OPD queue",
    s1Q1V: "34 active",
    s1Q2L: "Pharmacy",
    s1Q2V: "18 prescriptions",
    s1Q3L: "Follow-ups",
    s1Q3V: "22 due",
    s2Title: "Diagnostics Networks",
    s2Stats: "Linked reports",
    s2Desc:
      "Lab requests and reports stay attached to the right patient and consultation.",
    s2P1: "Lab Requests",
    s2P2: "Reports",
    s2Metric: "41",
    s2MetricLabel: "reports connected",
    s2Action: "Send CBC report for review",
    s2Q1L: "Requested",
    s2Q1V: "19 tests",
    s2Q2L: "Uploaded",
    s2Q2V: "14 reports",
    s2Q3L: "Doctor review",
    s2Q3V: "8 pending",
    s3Title: "Independent Doctors",
    s3Stats: "Less admin",
    s3Desc:
      "A simple digital practice workflow for doctors who want clarity without complexity.",
    s3P1: "Prescriptions",
    s3P2: "Follow-ups",
    s3Metric: "28",
    s3MetricLabel: "prescriptions issued",
    s3Action: "Schedule 3-day revisit",
    s3Q1L: "Today",
    s3Q1V: "16 appointments",
    s3Q2L: "Notes",
    s3Q2V: "9 updated",
    s3Q3L: "Reminders",
    s3Q3V: "5 follow-ups",
    headerTitle1: "Scale care operations",
    headerTitle2: "Built for clinics that want to grow without chaos",
    headerDescription:
      "DardiBook helps healthcare teams reduce manual work, strengthen patient connect, keep care information secure, and maintain a clear operational rhythm as the practice expands.",
    exploreDardiBookForTeams: "Explore DardiBook for teams",
    operationalSignal: "Operational signal",
    careFlowVisible: "Care flow visible",
    liveFlow: "Live flow",
    modulesUsed: "Modules used",
    nextBestAction: "Next best action",
    dardibookWorkflow: "DardiBook workflow",
  },
  FrontDoor: {
    h1Title: "Practice operating system",
    h1Subtitle: "One connected workspace for modern healthcare teams",
    h1Desc:
      "DardiBook helps clinics digitize daily operations, organize patient journeys, and keep doctors, staff, pharmacies, and diagnostics aligned from registration to follow-up.",
    h2Title: "Patient Management",
    h2Subtitle: "Keep every patient interaction easy to find",
    h2Desc:
      "Create patient profiles, view visit history, store clinical notes, and access prescriptions without digging through paper files or scattered spreadsheets.",
    h3Title: "Appointments",
    h3Subtitle: "Manage bookings, queues, and follow-ups",
    h3Desc:
      "Plan clinic schedules, track walk-ins, reduce missed visits, and keep every patient moving through the right stage of care.",
    h4Title: "Prescriptions",
    h4Subtitle: "Create clearer prescriptions and care instructions",
    h4Desc:
      "Generate digital prescriptions, record medication advice, and make it easier for patients and pharmacies to understand the next step.",
    seeAlso: "See also",
    h2List1: "Digital case history for every consultation",
    h2List2: "Quick search across patient records and visits",
    h2List3: "Staff-friendly workflows for reception and doctors",
    h3List1: "Daily appointment list for doctors and reception",
    h3List2: "Visit status updates from waiting to completed",
    h3List3: "Follow-up reminders for continued patient care",
    h4List1: "Repeat medicine and dosage references",
    h4List2: "Clearer instructions for patients",
    h4List3: "Fewer clarification calls from pharmacies",
    h5Title: "Diagnostics",
    h5Subtitle: "Coordinate lab requests and reports smoothly",
    h5Desc:
      "Share test recommendations, keep reports attached to the patient record, and help doctors review results with context during the next visit.",
    h5List1: "Lab requests linked to patient visits",
    h5List2: "Reports stored alongside medical history",
    h5List3: "Better coordination between clinics and diagnostics",
    p1Title: "Clinic Command Center",
    p1Subtitle: "Today across reception, doctors, pharmacy, and diagnostics",
    p1StatLabel: "scheduled visits",
    p1R1C1: "Waiting",
    p1R1C2: "12 patients",
    p1R1C3: "Reception",
    p1R2C1: "In consultation",
    p1R2C2: "6 patients",
    p1R2C3: "Doctors",
    p1R3C1: "Reports pending",
    p1R3C2: "7 files",
    p1R3C3: "Diagnostics",
    p2Title: "Patient Timeline",
    p2Subtitle: "One profile for history, notes, prescriptions, and files",
    p2StatLabel: "linked visits",
    p2R1C1: "Last visit",
    p2R1C2: "Fever and cough",
    p2R1C3: "12 Jun",
    p2R2C1: "Prescription",
    p2R2C2: "3 medicines",
    p2R2C3: "Active",
    p2R3C1: "Attached files",
    p2R3C2: "CBC report",
    p2R3C3: "Reviewed",
    p3Title: "Appointment Desk",
    p3Subtitle: "Bookings, walk-ins, queue status, and follow-up reminders",
    p3StatLabel: "next consultation",
    p3R1C1: "Riya Patel",
    p3R1C2: "Waiting",
    p3R1C3: "14:00",
    p3R2C1: "Amit Shah",
    p3R2C2: "In room 2",
    p3R2C3: "14:15",
    p3R3C1: "Mira Joshi",
    p3R3C2: "Follow-up",
    p3R3C3: "14:30",
    p4Title: "Digital Prescription",
    p4Subtitle: "Medication advice that stays attached to the visit record",
    p4StatLabel: "issued today",
    p4R1C1: "Paracetamol",
    p4R1C2: "500 mg",
    p4R1C3: "After food",
    p4R2C1: "Cough syrup",
    p4R2C2: "10 ml",
    p4R2C3: "Night",
    p4R3C1: "Review",
    p4R3C2: "3 days",
    p4R3C3: "Follow-up",
    p5Title: "Diagnostics Review",
    p5Subtitle: "Lab requests and reports available in clinical context",
    p5StatLabel: "reports pending",
    p5R1C1: "CBC",
    p5R1C2: "Received",
    p5R1C3: "Needs review",
    p5R2C1: "Lipid profile",
    p5R2C2: "Requested",
    p5R2C3: "Lab",
    p5R3C1: "X-ray chest",
    p5R3C2: "Uploaded",
    p5R3C3: "Reviewed",
    panelLive: "Live",
    panelFocusMetric: "Focus metric",
    panelRoleBasedAccess: "Role-based access",
    panelSearchPlaceholder: "Patient, visit, report, prescription",
    panelIconDoctor: "Doctor",
    panelIconRecords: "Records",
    panelIconLabs: "Labs",
  },
};

export default content;