const content = {
  Footer: {
    title: "Digitize every clinic touchpoint with DardiBook.",
    description:
      "Practice management software for appointments, patient records, prescriptions, diagnostics, pharmacy coordination, and follow-ups.",
    bookWalkthrough: "Book a product walkthrough",
    proof1Title: "Privacy-first workflows",
    proof1Desc:
      "Built around responsible handling of clinic and patient data.",
    proof2Title: "Guided setup",
    proof2Desc:
      "Map your current reception, consultation, and follow-up flow.",
    proof3Title: "Fast daily use",
    proof3Desc: "Designed for busy teams that need clarity during OPD hours.",
    productTitle: "Product",
    productPatientRecords: "Patient Records",
    productAppointments: "Appointments",
    productPrescriptions: "Prescriptions",
    productDiagnostics: "Diagnostics",
    solutionsTitle: "Solutions",
    solutionsSoloDoctors: "Solo Doctors",
    solutionsClinics: "Clinics",
    solutionsHospitals: "Hospitals",
    solutionsCareTeams: "Care Teams",
    workflowsTitle: "Workflows",
    workflowsPatientJourney: "Patient Journey",
    workflowsClinicQueue: "Clinic Queue",
    workflowsLabPharmacy: "Lab & Pharmacy",
    workflowsFollowups: "Follow-ups",
    companyTitle: "Company",
    companyBookDemo: "Book Demo",
    companyImplementation: "Implementation",
    companyTrustAccess: "Trust & Access",
    companyContact: "Contact",
    legalTitle: "Legal",
    legalAbout: "About",
    legalPricing: "Pricing",
    legalPrivacyPolicy: "Privacy Policy",
    legalTermsConditions: "Terms & Conditions",
    legalCancellationPolicy: "Cancellation Policy",
    copyright: "© {year} DardiBook, All rights reserved",
  },
  CallToAction: {
    title: "Ready to see DardiBook inside your clinic workflow?",
    description:
      "Book a walkthrough for your team. We will map your current reception, consultation, prescription, lab, and follow-up process to the right DardiBook setup.",
    bookDemo: "Book a Demo",
    pricingTitle: "Simple clinic pricing",
    pricingDesc:
      "Choose a plan around your users, branches, and workflow needs without paying for modules you do not use.",
    onboardingTitle: "Guided onboarding",
    onboardingDesc:
      "Get help setting up patient records, staff roles, appointment flow, prescriptions, and diagnostics from day one.",
  },
  FeaturesSequence: {
    headerSubtitle: "Designed for care teams",
    headerTitle: "Run your practice with less admin and more clarity",
    headerDesc:
      "DardiBook brings appointments, patient records, prescriptions, lab requests, follow-ups, and clinic activity into one simple workspace so doctors and staff can spend more time on patient care.",
    exploreModules: "Explore modules",
    todayLabel: "Today",
    clinicDeskTitle: "Clinic desk",
    liveLabel: "Live",
    waitingLabel: "Waiting",
    waitingValue: "12 patients",
    prescriptionsLabel: "Prescriptions",
    prescriptionsValue: "28 issued",
    labReportsLabel: "Lab reports",
    labReportsValue: "7 pending",
    nextConsultationLabel: "Next consultation",
    f1Title: "Digital Patient Records",
    f1Desc:
      "Keep medical history, visits, prescriptions, files, and notes organized for quick review during every consultation.",
    f1Cta: "View records",
    f2Title: "Appointment Workflow",
    f2Desc:
      "Manage bookings, queues, reminders, and follow-ups from one place without losing track of the day.",
    f2Cta: "See scheduling",
    f3Title: "Prescription & Lab Flow",
    f3Desc:
      "Create digital prescriptions and connect recommended tests with diagnostics for smoother patient handoffs.",
    f3Cta: "Explore care flow",
    f4Title: "Secure Practice Data",
    f4Desc:
      "Protect clinic information with role-aware access and a digital workflow built for responsible healthcare use.",
    f4Cta: "Review access",
  },
  TrustProof: {
    title: "Why clinics choose DardiBook",
    subtitle: "Less manual work, better patient continuity",
    description:
      "The strongest healthcare software feels calm during a busy clinic day. DardiBook keeps the essentials visible without forcing teams into a complicated enterprise system.",
    i1Title: "Secure clinic records",
    i1Desc:
      "Keep sensitive patient information organized with privacy-first digital workflows.",
    i2Title: "Role-based staff access",
    i2Desc:
      "Give reception, doctors, and operations teams the right view for their work.",
    i3Title: "Fast onboarding",
    i3Desc:
      "Start with core clinic workflows first, then expand into pharmacy, labs, and follow-ups.",
    i4Title: "Built for teams",
    i4Desc:
      "Works for solo doctors, growing clinics, hospitals, pharmacies, and diagnostics.",
  },
  ObjectionsAccordion: {
    title: "Frequently Asked Questions",
    description: "Everything you need to know about our product, billing, and how we keep your data secure. Select a topic below to explore.",
    
    contactTitle: "Still have questions?",
    contactDesc: "Can't find the answer you're looking for? Our friendly team is ready to help you get the most out of our platform.",
    contactButton: "Contact Support",
  },
  FAQData: [
    {
      id: "general",
      title: "General Questions",
      items: [
        { question: "What is DardiBook and how does it work?", answer: "DardiBook is a practice management software that digitizes every clinic touchpoint. It provides a seamless connected experience for managing appointments, patient records, prescriptions, diagnostics, and follow-ups." },
        { question: "Who is this solution built for?", answer: "It is designed for solo doctors, growing clinics, hospitals, pharmacies, and diagnostic centers who want to scale their operations and reduce administrative workloads." },
        { question: "Can DardiBook handle multi-doctor clinics?", answer: "Yes, DardiBook is designed to support both solo practitioners and multi-speciality clinics, with role-based access for different doctors, receptionists, and staff." },
        { question: "Do patients need to download an app?", answer: "No, patients receive their digital prescriptions, lab reports, and follow-up reminders directly via SMS or WhatsApp, without needing to install a separate application." },
        { question: "Can I use DardiBook on my mobile device or tablet?", answer: "Yes, DardiBook is cloud-based and fully responsive, meaning you can access it securely from any web browser on your smartphone, tablet, or desktop." },
        { question: "How does DardiBook help reduce patient wait times?", answer: "By streamlining the appointment queue and providing real-time status updates, front-desk staff can manage walk-ins and scheduled visits efficiently, reducing bottlenecks." },
        { question: "Do I need any special hardware to run DardiBook?", answer: "No special hardware is required. Any standard computer, tablet, or smartphone with an active internet connection is sufficient to run DardiBook." },
        { question: "Can DardiBook support multiple clinic branches?", answer: "Yes, our platform is built to handle multiple locations. You can manage patient records, staff, and analytics across all your branches from a single centralized dashboard." }
      ]
    },
    {
      id: "pricing",
      title: "Pricing & Billing",
      items: [
        { question: "Is there a free trial available?", answer: "Yes! We offer a 14-day free trial on all of our premium plans. No credit card is required to sign up." },
        { question: "Can I change my plan later?", answer: "Absolutely. You can upgrade or downgrade your plan at any time directly from your billing dashboard. Changes are prorated automatically." },
        { question: "Do I have to pay for modules I do not use?", answer: "No, our pricing is flexible. You can choose a plan around your users, branches, and specific workflow needs, ensuring you only pay for the features you use." },
        { question: "Are there any hidden setup fees?", answer: "No, there are no hidden charges. Our guided onboarding is included to help you set up patient records, staff roles, and appointment flows right from day one." },
        { question: "What payment methods do you accept?", answer: "We accept all major credit and debit cards, secure bank transfers, and popular digital wallets. Billing can be configured for monthly or annual cycles." },
        { question: "Is there a discount for annual subscriptions?", answer: "Yes, we offer a significant discount if you choose to be billed annually instead of monthly. Please check our pricing page for exact rates." },
        { question: "What happens to my data if I cancel my subscription?", answer: "Your data is always yours. If you decide to cancel, you will have a 30-day grace period to export all your patient records and clinic data before it is securely deleted from our servers." },
        { question: "Are updates and new features included in my subscription?", answer: "Absolutely! All system updates, security patches, and new features added to your current modules are included at no extra cost." }
      ]
    },
    {
      id: "support",
      title: "Support & Security",
      items: [
        { question: "How do I contact customer support?", answer: "You can reach out to our support team 24/7 via the live chat widget in the bottom right corner, or by emailing support." },
        { question: "Is patient data secure?", answer: "Security is our top priority. We use privacy-first workflows, industry-standard encryption, and role-based access to ensure sensitive health information is fully protected." },
        { question: "What kind of training or onboarding is provided?", answer: "We provide a comprehensive product walkthrough, guided setup assistance, and ongoing support to ensure your entire team—from reception to doctors—is comfortable using the system." },
        { question: "Are you compliant with healthcare data protection regulations?", answer: "Yes, DardiBook is built with strict adherence to global healthcare data privacy standards, ensuring secure storage, encryption, and safe handling of all medical records." },
        { question: "How often is the data backed up?", answer: "We perform automated, encrypted backups multiple times a day across secure servers to ensure zero data loss and maximum availability in case of emergencies." },
        { question: "Can I restrict access for certain staff members?", answer: "Yes. DardiBook features granular role-based access control. You can limit what receptionists, nurses, and doctors can view or edit based on their specific responsibilities." },
        { question: "What happens if the system goes offline?", answer: "DardiBook is hosted on highly reliable cloud infrastructure with 99.9% uptime. In the rare event of an outage, our 24/7 technical team is immediately alerted to resolve the issue as fast as possible." },
        { question: "Is two-factor authentication (2FA) available?", answer: "Yes, we strongly encourage enabling two-factor authentication for all clinic staff to add an extra layer of security when logging into the system." }
      ]
    },
    {
      id: "workflows",
      title: "Workflows & Features",
      items: [
        { question: "How does DardiBook manage lab and pharmacy workflows?", answer: "Doctors can create digital prescriptions and test requests during consultations. These are instantly accessible by your connected pharmacy and diagnostic teams, keeping reports attached to the patient's visit." },
        { question: "Can I access patient records during a consultation?", answer: "Absolutely. The patient timeline gives you a complete view of medical history, previous visit notes, active prescriptions, and attached files, all on one screen." },
        { question: "Does the system support walk-ins and queues?", answer: "Yes, the Appointment Desk allows reception to manage scheduled bookings, track walk-ins, and update queue status from 'waiting' to 'in consultation' in real-time." },
        { question: "Can I customize my digital prescription templates?", answer: "Yes, you can fully customize your prescription layout to include your clinic's logo, doctor signatures, specific fields, and preferred medical abbreviations." },
        { question: "How does the follow-up reminder system work?", answer: "DardiBook automatically sends SMS or WhatsApp reminders to patients for their upcoming follow-up visits based on the timeline set by the doctor during the initial consultation." },
        { question: "Is there an analytics dashboard for clinic performance?", answer: "Yes, you can track daily footfall, revenue, appointment trends, and module usage through an intuitive analytics dashboard built directly into the system." },
        { question: "Can doctors use voice-to-text for clinical notes?", answer: "Yes, DardiBook supports standard voice-to-text dictation tools available on your mobile or desktop device, making it faster to capture detailed consultation notes." },
        { question: "Can I upload past medical records and external lab reports?", answer: "Absolutely. You can scan and upload physical reports, X-rays, and past prescriptions directly into a patient's digital timeline for comprehensive care history." }
      ]
    },
    {
      id: "migration",
      title: "Onboarding & Data Migration",
      items: [
        { question: "Can you help us migrate data from our old software?", answer: "Yes, our dedicated onboarding team provides data migration assistance to safely transfer your existing patient profiles, past records, and appointment histories into DardiBook." },
        { question: "How long does it take to implement DardiBook?", answer: "Most solo clinics can be fully set up within 24 hours. Larger hospitals or multi-branch clinics typically take a few days, including staff training and workflow customization." },
        { question: "Will my clinic operations be disrupted during the transition?", answer: "Not at all. We phase the implementation step-by-step—usually starting with appointments and prescriptions—so your daily operations continue smoothly without interruption." },
        { question: "Can we import our existing medicine database?", answer: "Yes, you can upload your preferred medicine list, frequent dosages, and pharmacy inventory via CSV, making it instantly available in the digital prescription module." },
        { question: "Do you provide on-site training for staff?", answer: "While our primary onboarding is conducted virtually through comprehensive guided sessions, we can arrange on-site training for larger hospital deployments upon request." },
        { question: "What format should my old data be in for migration?", answer: "We accept standard formats like CSV, Excel, and SQL exports. Our team will guide you on how to extract this data from your legacy system." },
        { question: "Is there a dedicated account manager assigned to us?", answer: "Premium and Enterprise plans include a dedicated technical account manager who will assist you during setup and provide ongoing strategic support." }
      ]
    }
  ],

  Workflow: {
    title: "How DardiBook works",
    subtitle: "A complete patient journey from entry to follow-up",
    description:
      "DardiBook is built around the way clinics actually move: reception, consultation, prescription, diagnostics, and continued care.",
    s1Title: "Register Patient",
    s1Desc:
      "Create a patient profile once and keep demographics, visits, files, and care notes organized.",
    s2Title: "Consultation",
    s2Desc:
      "Doctors can review history, capture clinical notes, and keep each visit linked to the patient record.",
    s3Title: "Prescription",
    s3Desc:
      "Generate clear digital prescriptions with medicine, dosage, advice, and revisit instructions.",
    s4Title: "Lab & Pharmacy",
    s4Desc:
      "Connect test requests, pharmacy details, and reports back to the same visit for better continuity.",
    s5Title: "Follow-up",
    s5Desc:
      "Track pending care tasks and follow-up reminders so patients do not disappear after the visit.",
  },
  LogoCloud: {
    title: "Trusted by Healthcare Professionals",
    description:
      "DardiBook supports clinics, hospitals, pharmacies, diagnostics, and solo practitioners. Designed for modern medical workflows.",
    l1: "Clinics",
    l2: "Hospitals",
    l3: "Solo Doctors",
    l4: "Reception Teams",
    l5: "Care Coordinators",
    l6: "Patient Records",
    l7: "Appointments",
    l8: "Prescriptions",
    l9: "Lab Requests",
    l10: "Follow-ups",
    l11: "Pharmacies",
    l12: "Diagnostics",
    l13: "Specialists",
    l14: "Medical Staff",
    l15: "Patients",
  },
  Hero: {
    title: "Digitize your medical practice with DardiBook",
    description:
      "Manage appointments, patient records, prescriptions, lab requests, and follow-ups from one secure workspace built for doctors and clinic teams.",
    requestDemo: "Request Demo",
    seeWorkflow: "See Workflow",
    dummyClinic: "DardiBook Clinic",
  },
  Navbar: {
    menuWorkflow: "Workflow",
    menuModules: "Modules",
    menuTrust: "Trust",
    menuDemo: "Demo",
    modPatientRecordsTitle: "Patient Records",
    modPatientRecordsDesc:
      "Profiles, medical history, visit notes, files, and case context in one place.",
    modAppointmentsTitle: "Appointments",
    modAppointmentsDesc:
      "Clinic schedules, walk-ins, queues, visit status, and follow-up planning.",
    modPrescriptionsTitle: "Prescriptions",
    modPrescriptionsDesc:
      "Digital prescriptions with medicine, dosage, advice, and revisit instructions.",
    modDiagnosticsTitle: "Diagnostics",
    modDiagnosticsDesc:
      "Lab requests and reports connected to the right patient visit.",
    solSoloDoctorsTitle: "Solo Doctors",
    solSoloDoctorsDesc:
      "A simple digital workflow for independent practices.",
    solClinicsTitle: "Clinics",
    solClinicsDesc:
      "Reception, doctors, pharmacy, and lab teams working from one system.",
    solHospitalsTitle: "Hospitals",
    solHospitalsDesc:
      "Structured records and role-aware workflows for larger teams.",
    solCareTeamsTitle: "Care Teams",
    solCareTeamsDesc:
      "Better coordination across staff, patients, pharmacies, and diagnostics.",
    brandName: "DardiBook",
    requestDemo: "Request Demo",
  },
  CardCarousel: {
    title: "Built for healthcare teams",
    description: "See how DardiBook connects your clinic's workflow.",
    dragToExplore: "Drag to explore",
    c1Title: "Clinics & Hospitals",
    c1Eyebrow: "Operations",
    c1Desc:
      "Digitize front-desk, consultation, prescription, and follow-up workflows in one practical clinic management system.",
    c1Stat: "One connected desk",
    c1T1: "Queues",
    c1T2: "Records",
    c1T3: "Reports",
    c2Title: "Doctors",
    c2Eyebrow: "Consultation",
    c2Desc:
      "Review patient history, write prescriptions, request tests, and continue care with fewer administrative interruptions.",
    c2Stat: "Faster visits",
    c2T1: "History",
    c2T2: "Rx",
    c2T3: "Notes",
    c3Title: "Patients",
    c3Eyebrow: "Care journey",
    c3Desc:
      "Give patients a smoother journey with organized visits, clearer instructions, digital prescriptions, and timely follow-ups.",
    c3Stat: "Better continuity",
    c3T1: "Visits",
    c3T2: "Advice",
    c3T3: "Follow-up",
    c4Title: "Pharmacies",
    c4Eyebrow: "Medicine flow",
    c4Desc:
      "Read prescription details clearly, reduce manual clarification, and support faster medicine fulfillment.",
    c4Stat: "Clearer Rx",
    c4T1: "Dosage",
    c4T2: "Medicine",
    c4T3: "Refills",
    c5Title: "Diagnostics",
    c5Eyebrow: "Lab workflow",
    c5Desc:
      "Link lab requests and reports with patient visits so doctors can review results in the right clinical context.",
    c5Stat: "Linked reports",
    c5T1: "Tests",
    c5T2: "Reports",
    c5T3: "Review",
    c6Title: "Healthcare Platforms",
    c6Eyebrow: "Ecosystem",
    c6Desc:
      "Extend patient engagement and care coordination with modules built around real clinic workflows.",
    c6Stat: "Modular setup",
    c6T1: "Integrations",
    c6T2: "Teams",
    c6T3: "Care",
    c7Title: "Medical Institutions",
    c7Eyebrow: "Institutional care",
    c7Desc:
      "Support institutional operations with structured case histories, visit records, and repeatable care processes.",
    c7Stat: "Structured cases",
    c7T1: "Training",
    c7T2: "Cases",
    c7T3: "Records",
    headerTitle: "Built for every kind of healthcare provider",
    headerDescription:
      "From small clinics to growing hospitals, and from individual doctors to diagnostic labs, DardiBook helps reduce administrative workload while improving patient continuity.",
  },
  GridCarousel: {
    title: "Tailored to your practice",
    subtitle: "Configured for the way your team works.",
    s0Title: "Multi-speciality Clinics",
    s0Stats: "One desk",
    s0Desc:
      "Appointments, visits, prescriptions, and reports coordinated across departments.",
    s0P1: "Patient Records",
    s0P2: "Appointments",
    s0Metric: "6",
    s0MetricLabel: "departments aligned",
    s0Action: "Route patient to cardiology",
    s0Q1L: "Reception",
    s0Q1V: "12 waiting",
    s0Q2L: "Doctors",
    s0Q2V: "6 in consultation",
    s0Q3L: "Diagnostics",
    s0Q3V: "7 reports pending",
    s1Title: "Growing Hospitals",
    s1Stats: "Central view",
    s1Desc:
      "Daily operations organized for doctors, reception, pharmacy, and diagnostic teams.",
    s1P1: "Queue Flow",
    s1P2: "Care Tasks",
    s1Metric: "124",
    s1MetricLabel: "visits tracked today",
    s1Action: "Review pending care tasks",
    s1Q1L: "OPD queue",
    s1Q1V: "34 active",
    s1Q2L: "Pharmacy",
    s1Q2V: "18 prescriptions",
    s1Q3L: "Follow-ups",
    s1Q3V: "22 due",
    s2Title: "Diagnostics Networks",
    s2Stats: "Linked reports",
    s2Desc:
      "Lab requests and reports stay attached to the right patient and consultation.",
    s2P1: "Lab Requests",
    s2P2: "Reports",
    s2Metric: "41",
    s2MetricLabel: "reports connected",
    s2Action: "Send CBC report for review",
    s2Q1L: "Requested",
    s2Q1V: "19 tests",
    s2Q2L: "Uploaded",
    s2Q2V: "14 reports",
    s2Q3L: "Doctor review",
    s2Q3V: "8 pending",
    s3Title: "Independent Doctors",
    s3Stats: "Less admin",
    s3Desc:
      "A simple digital practice workflow for doctors who want clarity without complexity.",
    s3P1: "Prescriptions",
    s3P2: "Follow-ups",
    s3Metric: "28",
    s3MetricLabel: "prescriptions issued",
    s3Action: "Schedule 3-day revisit",
    s3Q1L: "Today",
    s3Q1V: "16 appointments",
    s3Q2L: "Notes",
    s3Q2V: "9 updated",
    s3Q3L: "Reminders",
    s3Q3V: "5 follow-ups",
    headerTitle1: "Scale care operations",
    headerTitle2: "Built for clinics that want to grow without chaos",
    headerDescription:
      "DardiBook helps healthcare teams reduce manual work, strengthen patient connect, keep care information secure, and maintain a clear operational rhythm as the practice expands.",
    exploreDardiBookForTeams: "Explore DardiBook for teams",
    operationalSignal: "Operational signal",
    careFlowVisible: "Care flow visible",
    liveFlow: "Live flow",
    modulesUsed: "Modules used",
    nextBestAction: "Next best action",
    dardibookWorkflow: "DardiBook workflow",
  },
  FrontDoor: {
    h1Title: "Practice operating system",
    h1Subtitle: "One connected workspace for modern healthcare teams",
    h1Desc:
      "DardiBook helps clinics digitize daily operations, organize patient journeys, and keep doctors, staff, pharmacies, and diagnostics aligned from registration to follow-up.",
    h2Title: "Patient Management",
    h2Subtitle: "Keep every patient interaction easy to find",
    h2Desc:
      "Create patient profiles, view visit history, store clinical notes, and access prescriptions without digging through paper files or scattered spreadsheets.",
    h3Title: "Appointments",
    h3Subtitle: "Manage bookings, queues, and follow-ups",
    h3Desc:
      "Plan clinic schedules, track walk-ins, reduce missed visits, and keep every patient moving through the right stage of care.",
    h4Title: "Prescriptions",
    h4Subtitle: "Create clearer prescriptions and care instructions",
    h4Desc:
      "Generate digital prescriptions, record medication advice, and make it easier for patients and pharmacies to understand the next step.",
    seeAlso: "See also",
    h2List1: "Digital case history for every consultation",
    h2List2: "Quick search across patient records and visits",
    h2List3: "Staff-friendly workflows for reception and doctors",
    h3List1: "Daily appointment list for doctors and reception",
    h3List2: "Visit status updates from waiting to completed",
    h3List3: "Follow-up reminders for continued patient care",
    h4List1: "Repeat medicine and dosage references",
    h4List2: "Clearer instructions for patients",
    h4List3: "Fewer clarification calls from pharmacies",
    h5Title: "Diagnostics",
    h5Subtitle: "Coordinate lab requests and reports smoothly",
    h5Desc:
      "Share test recommendations, keep reports attached to the patient record, and help doctors review results with context during the next visit.",
    h5List1: "Lab requests linked to patient visits",
    h5List2: "Reports stored alongside medical history",
    h5List3: "Better coordination between clinics and diagnostics",
    p1Title: "Clinic Command Center",
    p1Subtitle: "Today across reception, doctors, pharmacy, and diagnostics",
    p1StatLabel: "scheduled visits",
    p1R1C1: "Waiting",
    p1R1C2: "12 patients",
    p1R1C3: "Reception",
    p1R2C1: "In consultation",
    p1R2C2: "6 patients",
    p1R2C3: "Doctors",
    p1R3C1: "Reports pending",
    p1R3C2: "7 files",
    p1R3C3: "Diagnostics",
    p2Title: "Patient Timeline",
    p2Subtitle: "One profile for history, notes, prescriptions, and files",
    p2StatLabel: "linked visits",
    p2R1C1: "Last visit",
    p2R1C2: "Fever and cough",
    p2R1C3: "12 Jun",
    p2R2C1: "Prescription",
    p2R2C2: "3 medicines",
    p2R2C3: "Active",
    p2R3C1: "Attached files",
    p2R3C2: "CBC report",
    p2R3C3: "Reviewed",
    p3Title: "Appointment Desk",
    p3Subtitle: "Bookings, walk-ins, queue status, and follow-up reminders",
    p3StatLabel: "next consultation",
    p3R1C1: "Riya Patel",
    p3R1C2: "Waiting",
    p3R1C3: "14:00",
    p3R2C1: "Amit Shah",
    p3R2C2: "In room 2",
    p3R2C3: "14:15",
    p3R3C1: "Mira Joshi",
    p3R3C2: "Follow-up",
    p3R3C3: "14:30",
    p4Title: "Digital Prescription",
    p4Subtitle: "Medication advice that stays attached to the visit record",
    p4StatLabel: "issued today",
    p4R1C1: "Paracetamol",
    p4R1C2: "500 mg",
    p4R1C3: "After food",
    p4R2C1: "Cough syrup",
    p4R2C2: "10 ml",
    p4R2C3: "Night",
    p4R3C1: "Review",
    p4R3C2: "3 days",
    p4R3C3: "Follow-up",
    p5Title: "Diagnostics Review",
    p5Subtitle: "Lab requests and reports available in clinical context",
    p5StatLabel: "reports pending",
    p5R1C1: "CBC",
    p5R1C2: "Received",
    p5R1C3: "Needs review",
    p5R2C1: "Lipid profile",
    p5R2C2: "Requested",
    p5R2C3: "Lab",
    p5R3C1: "X-ray chest",
    p5R3C2: "Uploaded",
    p5R3C3: "Reviewed",
    panelLive: "Live",
    panelFocusMetric: "Focus metric",
    panelRoleBasedAccess: "Role-based access",
    panelSearchPlaceholder: "Patient, visit, report, prescription",
    panelIconDoctor: "Doctor",
    panelIconRecords: "Records",
    panelIconLabs: "Labs",
  },
};

export default content;