import callToAction from "./call-to-action";
import cardCarousel from "./card-carousel";
import featuresSequence from "./features-sequence";
import footer from "./footer";
import frontDoor from "./front-door";
import gridCarousel from "./grid-carousel";
import hero from "./hero";
import logoCloud from "./logo-cloud";
import navbar from "./navbar";
import objectionsAccordion, { faqData } from "./objections";
import productShowcase from "./product-showcase";
import trustProof from "./trust-proof";
import workflow from "./workflow";

const content = {
  Footer: footer,
  CallToAction: callToAction,
  FeaturesSequence: {
    ...featuresSequence,
    f1Title: featuresSequence.features[0].title,
    f1Desc: featuresSequence.features[0].desc,
    f1Cta: featuresSequence.features[0].cta,
    f2Title: featuresSequence.features[1].title,
    f2Desc: featuresSequence.features[1].desc,
    f2Cta: featuresSequence.features[1].cta,
    f3Title: featuresSequence.features[2].title,
    f3Desc: featuresSequence.features[2].desc,
    f3Cta: featuresSequence.features[2].cta,
    f4Title: featuresSequence.features[3].title,
    f4Desc: featuresSequence.features[3].desc,
    f4Cta: featuresSequence.features[3].cta,
  },
  TrustProof: {
    ...trustProof,
    i1Title: trustProof.items[0].title,
    i1Desc: trustProof.items[0].desc,
    i2Title: trustProof.items[1].title,
    i2Desc: trustProof.items[1].desc,
    i3Title: trustProof.items[2].title,
    i3Desc: trustProof.items[2].desc,
    i4Title: trustProof.items[3].title,
    i4Desc: trustProof.items[3].desc,
  },
  ObjectionsAccordion: objectionsAccordion,
  FAQData: faqData,
  Workflow: {
    ...workflow,
    s1Title: workflow.steps[0].title,
    s1Desc: workflow.steps[0].desc,
    s2Title: workflow.steps[1].title,
    s2Desc: workflow.steps[1].desc,
    s3Title: workflow.steps[2].title,
    s3Desc: workflow.steps[2].desc,
    s4Title: workflow.steps[3].title,
    s4Desc: workflow.steps[3].desc,
    s5Title: workflow.steps[4].title,
    s5Desc: workflow.steps[4].desc,
  },
  LogoCloud: {
    ...logoCloud,
    l1: logoCloud.logos[0],
    l2: logoCloud.logos[1],
    l3: logoCloud.logos[2],
    l4: logoCloud.logos[3],
    l5: logoCloud.logos[4],
    l6: logoCloud.logos[5],
    l7: logoCloud.logos[6],
    l8: logoCloud.logos[7],
    l9: logoCloud.logos[8],
    l10: logoCloud.logos[9],
    l11: logoCloud.logos[10],
    l12: logoCloud.logos[11],
    l13: logoCloud.logos[12],
    l14: logoCloud.logos[13],
    l15: logoCloud.logos[14],
  },
  Hero: hero,
  Navbar: navbar,
  CardCarousel: {
    ...cardCarousel,
    c1Title: cardCarousel.cards[0].title,
    c1Eyebrow: cardCarousel.cards[0].eyebrow,
    c1Desc: cardCarousel.cards[0].desc,
    c1Stat: cardCarousel.cards[0].stat,
    c1T1: cardCarousel.cards[0].tags[0],
    c1T2: cardCarousel.cards[0].tags[1],
    c1T3: cardCarousel.cards[0].tags[2],
    c2Title: cardCarousel.cards[1].title,
    c2Eyebrow: cardCarousel.cards[1].eyebrow,
    c2Desc: cardCarousel.cards[1].desc,
    c2Stat: cardCarousel.cards[1].stat,
    c2T1: cardCarousel.cards[1].tags[0],
    c2T2: cardCarousel.cards[1].tags[1],
    c2T3: cardCarousel.cards[1].tags[2],
    c3Title: cardCarousel.cards[2].title,
    c3Eyebrow: cardCarousel.cards[2].eyebrow,
    c3Desc: cardCarousel.cards[2].desc,
    c3Stat: cardCarousel.cards[2].stat,
    c3T1: cardCarousel.cards[2].tags[0],
    c3T2: cardCarousel.cards[2].tags[1],
    c3T3: cardCarousel.cards[2].tags[2],
    c4Title: cardCarousel.cards[3].title,
    c4Eyebrow: cardCarousel.cards[3].eyebrow,
    c4Desc: cardCarousel.cards[3].desc,
    c4Stat: cardCarousel.cards[3].stat,
    c4T1: cardCarousel.cards[3].tags[0],
    c4T2: cardCarousel.cards[3].tags[1],
    c4T3: cardCarousel.cards[3].tags[2],
    c5Title: cardCarousel.cards[4].title,
    c5Eyebrow: cardCarousel.cards[4].eyebrow,
    c5Desc: cardCarousel.cards[4].desc,
    c5Stat: cardCarousel.cards[4].stat,
    c5T1: cardCarousel.cards[4].tags[0],
    c5T2: cardCarousel.cards[4].tags[1],
    c5T3: cardCarousel.cards[4].tags[2],
    c6Title: cardCarousel.cards[5].title,
    c6Eyebrow: cardCarousel.cards[5].eyebrow,
    c6Desc: cardCarousel.cards[5].desc,
    c6Stat: cardCarousel.cards[5].stat,
    c6T1: cardCarousel.cards[5].tags[0],
    c6T2: cardCarousel.cards[5].tags[1],
    c6T3: cardCarousel.cards[5].tags[2],
    c7Title: cardCarousel.cards[6].title,
    c7Eyebrow: cardCarousel.cards[6].eyebrow,
    c7Desc: cardCarousel.cards[6].desc,
    c7Stat: cardCarousel.cards[6].stat,
    c7T1: cardCarousel.cards[6].tags[0],
    c7T2: cardCarousel.cards[6].tags[1],
    c7T3: cardCarousel.cards[6].tags[2],
  },
  GridCarousel: gridCarousel,
  FrontDoor: frontDoor,
  ProductShowcase: productShowcase,
};

export default content;
