const footer = {
  title: "Digitize every clinic touchpoint with DardiBook.",
  description:
    "Practice management software for appointments, patient records, prescriptions, diagnostics, pharmacy coordination, and follow-ups.",
  bookWalkthrough: "Book a product walkthrough",
  proof1Title: "Privacy-first workflows",
  proof1Desc: "Built around responsible handling of clinic and patient data.",
  proof2Title: "Guided setup",
  proof2Desc: "Map your current reception, consultation, and follow-up flow.",
  proof3Title: "Fast daily use",
  proof3Desc: "Designed for busy teams that need clarity during OPD hours.",
  productTitle: "Product",
  productPatientRecords: "Patient Records",
  productAppointments: "Appointments",
  productPrescriptions: "Prescriptions",
  productDiagnostics: "Diagnostics",
  solutionsTitle: "Solutions",
  solutionsSoloDoctors: "Solo Doctors",
  solutionsClinics: "Clinics",
  solutionsHospitals: "Hospitals",
  solutionsCareTeams: "Care Teams",
  workflowsTitle: "Workflows",
  workflowsPatientJourney: "Patient Journey",
  workflowsClinicQueue: "Clinic Queue",
  workflowsLabPharmacy: "Lab & Pharmacy",
  workflowsFollowups: "Follow-ups",
  companyTitle: "Company",
  companyBookDemo: "Book Demo",
  companyImplementation: "Implementation",
  companyTrustAccess: "Trust & Access",
  companyContact: "Contact",
  legalTitle: "Legal",
  legalAbout: "About",
  legalPricing: "Pricing",
  legalPrivacyPolicy: "Privacy Policy",
  legalTermsConditions: "Terms & Conditions",
  legalCancellationPolicy: "Cancellation Policy",
  copyright: "© {year} DardiBook, All rights reserved",
};

export default footer;
