const gridCarousel = {
  title: "Tailored to your practice",
  subtitle: "Configured for the way your team works.",
  slides: [
    {
      id: 0,
      title: "Multi-speciality Clinics",
      stats: "One desk",
      desc: "Appointments, visits, prescriptions, and reports coordinated across departments.",
      products: ["Patient Records", "Appointments"],
      metric: "6",
      metricLabel: "departments aligned",
      action: "Route patient to cardiology",
      queue: [
        ["Reception", "12 waiting"],
        ["Doctors", "6 in consultation"],
        ["Diagnostics", "7 reports pending"],
      ],
    },
    {
      id: 1,
      title: "Growing Hospitals",
      stats: "Central view",
      desc: "Daily operations organized for doctors, reception, pharmacy, and diagnostic teams.",
      products: ["Queue Flow", "Care Tasks"],
      metric: "124",
      metricLabel: "visits tracked today",
      action: "Review pending care tasks",
      queue: [
        ["OPD queue", "34 active"],
        ["Pharmacy", "18 prescriptions"],
        ["Follow-ups", "22 due"],
      ],
    },
    {
      id: 2,
      title: "Diagnostics Networks",
      stats: "Linked reports",
      desc: "Lab requests and reports stay attached to the right patient and consultation.",
      products: ["Lab Requests", "Reports"],
      metric: "41",
      metricLabel: "reports connected",
      action: "Send CBC report for review",
      queue: [
        ["Requested", "19 tests"],
        ["Uploaded", "14 reports"],
        ["Doctor review", "8 pending"],
      ],
    },
    {
      id: 3,
      title: "Independent Doctors",
      stats: "Less admin",
      desc: "A simple digital practice workflow for doctors who want clarity without complexity.",
      products: ["Prescriptions", "Follow-ups"],
      metric: "28",
      metricLabel: "prescriptions issued",
      action: "Schedule 3-day revisit",
      queue: [
        ["Today", "16 appointments"],
        ["Notes", "9 updated"],
        ["Reminders", "5 follow-ups"],
      ],
    },
  ],
  headerTitle1: "Scale care operations",
  headerTitle2: "Built for clinics that want to grow without chaos",
  headerDescription:
    "DardiBook helps healthcare teams reduce manual work, strengthen patient connect, keep care information secure, and maintain a clear operational rhythm as the practice expands.",
  exploreDardiBook: "Explore DardiBook",
  operationalSignal: "Operational signal",
  careFlowVisible: "Care flow visible",
  liveFlow: "Live flow",
  modulesUsed: "Modules used",
  nextBestAction: "Next best action",
  dardibookWorkflow: "DardiBook workflow",
};

export default gridCarousel;
