export const APP_LINKS = {
  HOME: "/",
  DEMO: "/demo",
  WORKFLOW: "#workflow",
  TRUST: "#trust",
  MODULES: "#modules",
  BLOG: "/blog",
  PRICING: "/pricing",
  SECURITY: "/security",
  MAIN_CONTENT: "#main",
  DARDIBOOK_DASHBOARD: "https://dashboard.dardibook.in/",
  SOLUTIONS: {
    SOLO_DOCTORS: "/solutions/solo-doctors",
    CLINICS: "/solutions/clinics",
    HOSPITALS: "/solutions/hospitals",
  },
  DOCS: {
    ABOUT_US: "/docs/about-us",
    PRICING: "/docs/pricing",
    PRIVACY_POLICY: "/docs/privacy-policy",
    TERMS_CONDITIONS: "/docs/terms-conditions",
    CANCELLATION_POLICY: "/docs/cancellation-policy",
    CONTACT_US: "/docs/contact-us",
  },
};
