import type { Metadata } from "next";
import "./globals.css";
import { Alegreya_Sans } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Favicon.svg", // /public path
  },
};
const manrope = Alegreya_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.className}>
      <head>
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="bg-white" suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
